### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by rahulgovind** [hybridNeo/cs411-frontend#2]
- [x] Like/Unlike button for posts
- [x] Follow/Unfollow button for users
- [ ] Create posts with categories (currently they are not added to any category)
- [ ] Show all posts in a given topic
- [ ] Show a given user profile

Advanced 
- [ ] Recommended posts. Based on the users someone follows and the posts these users have liked.
- [ ] Recommended topics: Possibly based on the posts someone likes and the categories those posts belong to
- [ ] Advanced Object Search: Full-text search that goes through both posts (title, description and content) and users (username, bio)
- [ ] Trending: Show trending posts based on how old they are and how many likes they have
